#!/usr/bin/env bash
# يحدّث تعليق الحالة الواحد في PR #1 (يُعرَف بعلامة مخفية) أو ينشئه إن لم يوجد — بدل تعليق جديد في كل تشغيل
# الاستعمال: live-comment.sh <ملف-النص>
set -euo pipefail
BODY_FILE="$1"; MARK="<!-- live-server-status -->"; REPO="${GITHUB_REPOSITORY}"
BODY="$(cat "$BODY_FILE")"
# العلامة قبل ذيل التوقيع حتى يبقى الذيل آخر سطر
FOOTER=$'\n---\n_Generated by'
BODY="${BODY/${FOOTER}/$'\n'${MARK}${FOOTER}}"
ID="$(gh api "repos/${REPO}/issues/1/comments?per_page=100" --paginate --jq ".[] | select(.body | contains(\"${MARK}\")) | .id" 2>/dev/null | tail -1 || true)"
if [ -n "$ID" ] && gh api -X PATCH "repos/${REPO}/issues/comments/${ID}" -f body="$BODY" > /dev/null; then echo "حُدّث تعليق الحالة (${ID})"; exit 0; fi
gh api "repos/${REPO}/issues/1/comments" -f body="$BODY" > /dev/null && echo "أُنشئ تعليق الحالة" || echo "تعذّر نشر التعليق"
exit 0
